export const CARDS = [
      "{A} siéntate en las piernas de {B} o toma dos tragos.",
      "{A} abre Instagram y deja que {B} le dé like a todas las fotos de una persona que elija.",
      "{A} cuenta una vez que te hayan rejecteado o toma un shot para ahogar las penas.",
      "{A} haz un trust fall con {B} o toma dos tragos.",
      "{A} si eres el jugador más joven, toma dos tragos.",
      "Todos apunten al jugador que creen que va a estar soltero a los 40.",
      "{A} apaga tu celular por el resto del juego. Si lo quieres prender, bájate el trago.",
      "{A} mándale un DM a tu crush o bájate el trago.",
      "{A} hazle a {B} una pregunta de true or false sobre ti. Si {B} la tiene bien, {A} toma dos tragos. Si la tiene mal, {B} toma dos tragos.",
      "{A}: Fuck, Marry, Kill con las personas que {B} quiera.",
      "{A} llama a tu mamá y dile que te han arrestado o toma cinco tragos.",
      "{A} deja que el grupo mire tu search history o fondeate el trago.",
      "{A} toca la punta de la nariz con {B} por 60 segundos o ambos toman medio trago.",
      "{A} toma un sip por cada palabra sucia que digas por el resto de la ronda.",
      "{B}, ¿qué es una cosa sobre la que {A} es muy picky? Responde o ambos toman cinco tragos.",
      "{A} llama a tu mamá y dile que la amas o toma dos tragos.",
      "{A} dale tu celular a {B} y deja que haga lo que quiera por un minuto. Si no, fondeate el trago.",
      "{A} deja que el grupo mire tu gallery de fotos por 60 segundos o toma un shot.",
      "{A} y {B}, ustedes son los papás del grupo. Explíquenles cómo se hacen los bebés.",
      "{A}, ¿es {B} tu type? Responde por qué sí o por qué no, o toma un shot.",
      "{B} describe el partner perfecto de {A} o ambos toman tres tragos.",
      "{A}, ¿alguno de tus amigos gusta de {B}? Responde o toma cinco tragos.",
      "{A}, ¿alguno de tus amigos le cae mal {B}? Responde o toma cinco tragos.",
      "{B}, cierra tus ojos. {A}, adivina qué color son. Si fallas, tres tragos.",
      "Todos apuntan al jugador que se debe fondear el trago.",
      "Todas las personas con pelo chocolate toman.",
      "Todas las personas con pelo rubio toman.",
      "Todas las personas con pelo rojo toman.",
      "Todas las personas con pelo negro toman.",
      "Todos los hombres toman.",
      "Todas las mujeres toman.",
      "{A} y {B}, staring contest. El que pierde, cinco tragos.",
      "Waterfall. {A} empieza.",
      "Waterfall. {A} empieza.",
      "Waterfall. {A} empieza.",
      "Waterfall. {A} empieza.",
      "{A}, tómate un shot.",
      "{A}, ladra como un perro hasta nuevo aviso, o cinco tragos.||RULE||Ya puedes parar de ladrar",
      "Todos voten quién está más adicto a TikTok. Esa persona toma.",
      "{A}, cada vez que {B} tome, tú tomas hasta que te vuelva a tocar.",
      "{A}, pregunta pregunta. Tú comienzas.",
      "{A}, pregunta pregunta. Tú comienzas.",
      "{A}, pregunta pregunta. Tú comienzas.",
      "Tema: canciones de Luis Miguel. {A} empieza. Tres tragos el que falla.",
      "Tema: juegos de mesa. {A} empieza. Tres tragos el que falla.",
      "Tema: tipos de alcohol. {A} empieza. Tres tragos el que falla.",
      "Tema: aplicaciones de social media. {A} empieza. Tres tragos el que falla.",
      "{A} decide si el jugador a tu izquierda o derecha debe tomar cinco tragos.",
      "El que está poniendo la música reparte cinco tragos.",
      "{A}, el jugador a tu izquierda toma cinco tragos.",
      "{B}, el jugador a tu derecha toma cinco tragos.",
      "El que leyó esto se toma tres tragos.",
      "El último jugador que le tire algo a {A} tiene que acabarse su trago.",
      "Cada vez que vayan a decir algo tienes que decir 'mi amor' antes. Hasta la próxima ronda.||RULE||Ya pueden dejar de decir mi amor.",
      "{A} escoge un jugador. Todos menos ustedes dos toman tres tragos.",
      "{A} di una palabra. El de tu derecha tiene que decir una palabra que rime. El que falla, tres tragos.",
      "El jugador más viejo se acaba su bebida. Enséñala a los pequeñines.",
      "{A} ponte de espaldas y deja que un jugador te toque el hombro. Si adivinas quién fue, reparte cinco tragos. Si no, te los tomas.",
      "Tema: películas de Pixar. Empieza {A}.",
      "{A} cruza brazos con {B} y tómense cuatro tragos.",
      "Los que tengan la misma edad brinden y tomen dos tragos juntos.",
      "{A} escoge el jugador que parezca que tenga los zapatos más baratos. Ese jugador toma tres tragos.",
      "A la cuenta de tres todos voten Instagram o TikTok. La minoría toma.",
      "El último en tocar la pared toma cinco tragos.",
      "Todos tomen el número de alarmas que ponen en la mañana.",
      "El jugador con el vaso más vacío que se lo acabe y se sirva otro.",
      "Todos toman un trago por cada hermano que tengan.",
      "A la cuenta de tres, señala a cualquier jugador. Todos beben el número de dedos que le apuntaron.",
      "El que te dé la calificación de Uber más baja toma tres tragos.",
      "{A} y {B} están casados. Tienen que tomar lo mismo hasta que le toque a otro.",
      "{A}, di el nombre de una mascota de {B}. Si no sabes, bebe tres tragos.",
      "{A} toma tres tragos.",
      "{A} toma cinco tragos.",
      "{A} reparte tres tragos.",
      "{A} reparte cinco tragos.",
      "{B}, dile algo a {A}. Si {A} se pone rojo, toma tres tragos. Si no, tú los tomas.",
      "{B}, dile algo a {A}. Si {A} se ríe, toma tres tragos. Si no, tú los tomas.",
      "{A} califica a {B} del 1 al 10.||NEXT||{B} toma la calificación en tragos.",
      "Voten por el jugador más llorón. Ese toma tres tragos.||NEXT||Todos menos el llorón toman cinco tragos para consolarlo.",
      "Todos voten al jugador más básico.||NEXT||El jugador elegido puede vengarse y repartir cinco tragos.",
      "{A} escoge a alguien en quien confíes.||NEXT||Esa persona decide si te bajas el trago o no.",
      "{A} escoge a los dos jugadores con más tensión.||NEXT||Esos dos toman tres tragos para relajarse.",
      "{A} dile un secreto a {B}.||NEXT||Díganlo en voz alta o ambos se toman la mitad del trago.",
      "{B}, pregúntale verdad o reto a {A}.",
      "{B}, pregúntale verdad o reto a {A}.",
      "{A}, di de qué ciudad es {B}. Si fallas, toma tres tragos.",
      "{A}, di el mes de cumpleaños de {B}. Si fallas, toma tres tragos.",
      "{A}, di el nombre de uno de los padres de {B}. Si fallas, toma tres tragos.",
      "{A}, di alguna comida que no le gusta a {B}. Si fallas, toma tres tragos.",
      "{A}, di un green flag de {B}. Si no puedes, toma cinco tragos.",
      "{A}, di si {B} prefiere llamada o text. Si fallas, toma tres tragos.",
      "{A}, actúa como pirata hasta nuevo aviso.||RULE||Ya puedes dejar de actuar como pirata.",
      "{A} deja que {B} controle tus DMs por 30 segundos o toma tres tragos.",
      "{A} imita a {B} hasta la próxima ronda.||RULE||Ya puedes dejar de imitar.",
      "{A} inventa un rumor sobre {B}. Si es creíble, reparte tres tragos.",
      "{A} muestra la última foto que tomaste o toma dos tragos.",
      "{A} dile a {B} algo que nunca le hayas dicho o toma tres tragos.",
      "{A} manda un audio diciendo 'te extraño' a alguien que {B} diga o toma un shot.",
      "{A} deja que {B} te haga una pregunta incómoda.",
      "{A} mira fijamente a {B} por 30 segundos sin reírte.",
      "{A} di algo que a {B} le dé pena o ambos toman un shot.",
      "{A} imita a alguien del grupo. Si el grupo no adivina quién es, toma 5 tragos.",
      "{A} toma si alguna vez ghosteaste a alguien.",
      "{A} mándale 'estás despierto?' a alguien que el grupo escoja o un shot.",
      "{A} muestra tus recents de Instagram o toma un shot.",
      "{A} cuenta tu biggest crashout o toma 5 tragos.",
      "{A} di la persona que más te sorprendería que le gustes. Esa persona toma 3 tragos contigo.",
      "A la cuenta de 3, todos votan: ¿quién aquí se ilusiona demasiado rápido? Toma 3 tragos.",
      "{A} di algo que {B} nunca diría sobrio o toma 5 tragos.",
      "{A} di algo que a {B} le cuesta admitir. Si no, ambos se bajan el trago para guardar el secreto.",
      "A la cuenta de 3, todos votan: ¿quién aquí manda los voice messages más largos? Toma un trago por cada minuto.",
      "A la cuenta de 3, todos votan: ¿quién aquí volvería con su ex sin pensarlo? Toma tres tragos.",
      "A la cuenta de 3, todos votan: ¿quién aquí no sabe superar a alguien? Toma tres tragos.",
      "{A} di a qué edad {B} dio su primer beso; toma esa cantidad en tragos.",
      "A la cuenta de 3, todos votan: ¿quién aquí tiene el peor gusto? Toma 5 tragos.",
      "A la cuenta de 3, todos votan: ¿quién aquí es el más celoso? Toma 3 tragos.",
      "{A} y {B} compiten en quién aguanta más sin hablar. El que pierda toma 3 tragos.",
      "{A} lee el último mensaje de alguien que {B} escoja o toma cinco tragos.",
      "{A} mándale un chat a la persona que {B} escoja o toma medio trago.",
      "{A}: Fuck, Marry, Kill con las personas que {B} quiera.",
      "{A} dale like a una foto en Instagram de alguien que {B} escoja o toma cinco tragos.",
      "El siguiente jugador en recibir una notificación o mirar su celular toma tres tragos.",
      "{A} manda un sticker que {B} escoja en un grupo de 100+ personas o toma un shot.",
      "{A} inventa una historia. {B} tiene que adivinarla haciendo preguntas de sí o no. Si no la adivina, toma un shot.",
      "A la cuenta de tres, {A} pone dedo arriba o dedo abajo. Todos hacen lo mismo. Los que matcheen con {A} toman cinco tragos.",
      "Tema: calles de Panamá. {A} empieza. Tres tragos el que falla.",
      "{A} di un red flag de {B} o toma cinco tragos.",
      "{A}, di quién del grupo sería peor roommate o toma 5 tragos.",
      "{A}, di una opinión controversial sobre {B} o toma 5 tragos.",
      "{A}, quienes aqui harian la major pareja||NEXT||Salud por los novios!",
      " A la cuenta de tres votan ¿quien tiene el peor taste en gente?",
      "Tema: restaurantes de Panamá. {A} empieza.",
      "Tema: artistas latinos. {A} empieza.",
      "{A}, di quién sería peor persona para tener de enemigo. ||NEXT|| Esa persona escoge cuanto tomas",
      "{A}, di el segundo nombre de {B}. Si fallas, toma tres tragos.",
      "{A}, di el celebrity crush de {B}. Si fallas, toma tres tragos.",
      "{A}, deja que {B} responda tu próximo mensaje o tomas 5 tragos",
      "{A}, deja que el grupo te dé un nuevo apodo hasta la próxima ronda. Si no lo usan toman 1 trago. ||RULE||Ya pueden dejar el apodo.",
      "{A}, di qué jugador aquí sería tu worst mistake o toma 5 tragos para callarlo.",
      "{A}, di algo que crees que {B} hace cuando está enamorado. ||NEXT|| Tomate 5 tragos por Simp.",
      "{A}, deja que {B} mande un emoji a cualquier chat tuyo o toma cinco tragos.",
      "{A},  cuentanos la ultima vez que lloraste o toma 5 tragos ",
      "{A}, di qué jugador aquí parece más probable que siga obsesionado con alguien. ||NEXT|| tomate un shot a ver si se te olvida.",
      "{A},  Muestra tu Chatgpt logs o tomate un shot. ",
      "{A} y {B} agarrense la mano hasta nuevo aviso, si se sueltan, medio shot para cada uno.||RULE||Ya pueden parar de agararse la mano.",
      "{A}, deja que {B} escriba una frase en los Instagram notes o toma 6 tragos.",
      "{A}, busca 'te extraño' en tus chats o toma cinco tragos.",
      "{A}, deja que el grupo vea quién es tu best friend #1 en Snapchat o toma.",
      "{A}, deja que {B} responda una historia de Instagram desde tu cuenta o toma un shot.",
      "{A}, manda 'JAJAJAJA' al último chat que tengas abierto sin contexto o toma 5 tragos.",
      "{A}, manda un 'buenas noches' a alguien que {B} escoja o toma 5 tragos.",
      "{A}, mándale 'te vi hoy y me acordé de ti' a alguien; {B} escoje la persona y lo que manda o toma un shot.",
 ];
